#!/bin/sh
# bcomp file.b out -- compile B with aap's self-hosted B compiler (bc + ba, threaded code) and link
set -e
B=/opt/b/amd64
t=$(mktemp -d)
trap 'rm -rf "$t"' EXIT
"$B/bc" "$1" "$t/p.i"
"$B/ba" "$t/p.i" "$t/p.s"
cc -no-pie -o "$2" "$B/brt1.s" "$t/p.s" "$B/brt2.s" "$B/printn.s" "$B/printf.s" "$B/libb.s" "$B/bilib.s"
